name: platina
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.0.1
  freezed: ^2.0.3+1
  built_value: ^8.1.2
  dartz: ^0.10.0
  chopper: ^6.1.0
  lottie: ^2.2.0
  freezed_annotation: ^2.0.3
  # connectivity_plus: ^4.0.2
  #
  provider: ^6.0.1

  #ui
  easy_localization: ^3.0.0
  flutter_screenutil: ^5.5.4
  image_cropper: ^3.0.1
  progress_indicators: ^1.0.0
  flutter_easyloading: ^3.0.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.2.0
  flutter_svg: ^1.0.3
  bloc: ^8.1.2
  connectivity_bloc: ^0.0.3
  connectivity_plus: ^4.0.2
  built_collection: ^5.1.1
  cached_network: ^1.0.1
  html: ^0.15.4
  simple_html_css: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  chopper_generator: ^6.0.0
  built_value_generator: ^8.1.2
  # flutter_bloc_generator: ^1.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/svg/
    - assets/translation/
